---
repos:
  - repo: local
    hooks:
      - id: just _git::pre-commit
        name: just _git::pre-commit
        entry: just _git::pre-commit
        language: unsupported
        pass_filenames: false
